name: flutter_svg_editor
description: >
  A Flutter package for editing SVG files with color, rotation, AI optimization,
  and animation tools. Supports web, mobile, and desktop apps.
version: 1.0.4
homepage: https://github.com/Rajkumar-coderm/flutter_svg_editor

environment:
  sdk: ^3.5.1
  flutter: ">=3.3.0"

dependencies:
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.0.10+1
  flutter_web_plugins:
    sdk: flutter
  path_provider: ^2.1.4
  plugin_platform_interface: ^2.1.8
  web: ^1.0.0
  xml: ^6.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_svg_editor
        pluginClass: FlutterSvgEditorPlugin
      ios:
        pluginClass: FlutterSvgEditorPlugin
      linux:
        pluginClass: FlutterSvgEditorPlugin
      macos:
        pluginClass: FlutterSvgEditorPlugin
      windows:
        pluginClass: FlutterSvgEditorPluginCApi
      web:
        pluginClass: FlutterSvgEditorWeb
        fileName: flutter_svg_editor_web.dart

  uses-material-design: true
  assets:
    - assets/both.svg
    - assets/horizontal.svg
    - assets/original.svg
    - assets/vertical.svg
